### PR TITLE
Version 050

### PR DESCRIPTION
**Pull request by MyreMylar**
Version 0.5.0 is finished.

### CODE REVIEW

**Comment by MyreMylar** [comment]
Just got to figure out these failing tests on older python versions...

**Comment by Snayff** [comment]
The new version looks excellent, with some great new features. Thank you for all of your hard work, mate.

**Comment by MyreMylar** [comment]
It's done but not on PyPI yet, because PyPI seems to be down for uploads this morning. 

Sods law eh? I'll check throughout the day to see if it gets fixed.

**Comment by MyreMylar** [comment]
...And it's back up. build should be live on PyPI now so you can pip install pygame_gui -U it. Or however people are grabbing their modules these days.

**Pull request merged**
