### PR TITLE
Add on_pressed method

### PR DESCRIPTION
**Pull request by LondonClass**
This way, custom click events will be available.

By the way, UIStatusBar has a percent_method property to calculate the percentage. I wonder if UIButton can also have an on_click_method property to record the event after being clicked?

### CODE REVIEW

**Comment by MyreMylar** [comment]
Is the purpose of this to override the standard button Event generation? E.g. to make a button that doesn't generate some of these events?

I'm just wondering what problem this is trying to solve from your perspective, that responding to the events in the event loop doesn't? Is it the one frame delay in response time?

**Review by MyreMylar — APPROVED** [review]
OK, committing this refactor as it seems to work fine and people might find it useful.

**Comment by LondonClass** [comment]
Thank you for merging the pull request. However, I hope you are aware of the usage regarding this. This might be useful when creating a simple button. For example, in the Quick Start Guide case, we can set the on_pressed attribute of the button to a function that will directly print "Hello World!" when the button is pressed, replacing the code that checks the event type of the button in the main loop.

{~$7L75GFF04JQFF7JL6{%C
Y$)}4}6S$LN%NOSNE@DZ(5G

**Comment by LondonClass** [comment]
> OK, committing this refactor as it seems to work fine and people might find it useful.

Thank you for merging the pull request. However, I hope you are aware of the usage regarding this. This might be useful when creating a simple button. For example, in the Quick Start Guide case, we can set the on_pressed attribute of the button to a function that will directly print "Hello World!" when the button is pressed, replacing the code that checks the event type of the button in the main loop.

{~$7L75GFF04JQFF7JL6{%C
Y$)}4}6S$LN%NOSNE@DZ(5G

**Pull request merged**
